#{Matthew_Hill
part1: Listing4_1.c Listing4_2.c Listing4_3.c Listing4_4.c Listing4_5.c
	gcc -pthread -lrt -o Listing4_1 Listing4_1.c
	gcc -pthread -lrt -o Listing4_2 Listing4_2.c
	gcc -pthread -lrt -o Listing4_3 Listing4_3.c
	gcc -pthread -lrt -o Listing4_4 Listing4_4.c
	gcc -pthread -lrt -o Listing4_5 Listing4_5.c
	
